### ISSUE TITLE
vSphere always fails 

### ISSUE THREAD

**Issue by beandj** [openshift/okd#277]
**Describe the bug**
Vsphere installation with IPI always fail

openshift-install create cluster --dir=path --log-level=info

**Version**
4.5.0-0.okd-2020-07-14-153706-ga

**How reproducible**
Every time got a different error! But allways on crio.log

**Log bundle**
[log-bundle-20200722210638.tar.gz](https://github.com/openshift/okd/files/4963427/log-bundle-20200722210638.tar.gz)
[log-bundle-20200722214232.tar.gz](https://github.com/openshift/okd/files/4963428/log-bundle-20200722214232.tar.gz)

A 44MB logfile (in this the master was created but with error)
https://www.dropbox.com/s/2gjdq2abv1qxdh9/log-bundle-20200722202652.tar.gz?dl=0

**Comment by vrutkovs** [comment]
That looks very similar to https://github.com/openshift/okd/issues/276

**Comment by vrutkovs** [comment]
kubelet panics:
```
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: runtime stack:
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: runtime.throw(0x43dc603, 0x23)
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]:         /usr/local/go/src/runtime/panic.go:774 +0x72
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: runtime.gentraceback(0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0xc000401080, 0x0, 0x0, 0x7fffffff, 0x44ff9c0, 0x7fce0fb3ebc0, 0x0, ...)
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]:         /usr/local/go/src/runtime/traceback.go:545 +0x1987
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: runtime.copystack(0xc000401080, 0x1000, 0x1)
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]:         /usr/local/go/src/runtime/stack.go:886 +0x25a
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: runtime.newstack()
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]:         /usr/local/go/src/runtime/stack.go:1055 +0x2fb
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: runtime.morestack()
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]:         /usr/local/go/src/runtime/asm_amd64.s:449 +0x8f
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: goroutine 131 [copystack]:
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: created by
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]:         ?:0 +0x7422ad
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: goroutine 1 [select]:
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: runtime.gopark(0x44ffc90, 0x0, 0x1809, 0x1)
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]:         /usr/local/go/src/runtime/proc.go:304 +0xe0
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: runtime.selectgo(0xc0009dfee0, 0xc0009dfd38, 0x4, 0x435c173, 0x4)
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]:         /usr/local/go/src/runtime/select.go:313 +0xc9b
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: goroutine 19 [chan receive]:
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: github.com/openshift/origin/vendor/k8s.io/klog.(*loggingT).flushDaemon(0x7437060)
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]:         /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/klog/klog.go:1010 +0x8b
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: created by github.com/openshift/origin/vendor/k8s.io/klog.init.0
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]:         /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/klog/klog.go:411 +0xd6
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: goroutine 68 [sleep]:
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: runtime.goparkunlock(...)
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]:         /usr/local/go/src/runtime/proc.go:310
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: time.Sleep(0x3b9aca00)
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]:         /usr/local/go/src/runtime/time.go:105 +0x157
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/scheduler/framework/v1alpha1.(*metricsRecorder).run(0xc00013e810)
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]:         /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/scheduler/framework/v1alpha1/metrics_recorder.go:87 +0x3f
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: created by github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/scheduler/framework/v1alpha1.newMetricsRecorder
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]:         /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/scheduler/framework/v1alpha1/metrics_recorder.go:59 +0x104
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: goroutine 114 [chan receive]:
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server.SetupSignalHandler.func1(0xc0000ba9c0)
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]:         /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/signal.go:38 +0x36
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: created by github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server.SetupSignalHandler
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]:         /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/signal.go:37 +0xdc
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: goroutine 97 [select]:
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x44fdb60, 0x4b07d80, 0xc0003ce1b0, 0x1, 0xc0000ba0c0)
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]:         /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:167 +0x13f
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x44fdb60, 0x12a05f200, 0x0, 0xc00038f901, 0xc0000ba0c0)
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]:         /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0xaa
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/wait.Until(...)
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]:         /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/wait.Forever(0x44fdb60, 0x12a05f200)
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]:         /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:81 +0x4f
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: created by github.com/openshift/origin/vendor/k8s.io/component-base/logs.InitLogs
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]:         /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/component-base/logs/logs.go:58 +0x8a
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: goroutine 74 [select]:
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: github.com/openshift/origin/vendor/go.opencensus.io/stats/view.(*worker).start(0xc00080e730)
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]:         /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/go.opencensus.io/stats/view/worker.go:154 +0x100
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: created by github.com/openshift/origin/vendor/go.opencensus.io/stats/view.init.0
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]:         /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/go.opencensus.io/stats/view/worker.go:32 +0x57
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: goroutine 96 [syscall]:
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: os/signal.signal_recv(0x462226)
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]:         /usr/local/go/src/runtime/sigqueue.go:147 +0x9c
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: os/signal.loop()
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]:         /usr/local/go/src/os/signal/signal_unix.go:23 +0x22
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: created by os/signal.init.0
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]:         /usr/local/go/src/os/signal/signal_unix.go:29 +0x41
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: goroutine 78 [select]:
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000362f40, 0x4b07d80, 0xc000928000, 0x1, 0xc0000ba0c0)
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]:         /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:167 +0x13f
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000362f40, 0x2540be400, 0x0, 0xc0007a9e01, 0xc0000ba0c0)
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]:         /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0xaa
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc000362f40, 0x2540be400, 0xc0000ba0c0)
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]:         /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: created by github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubelet/certificate.addCertRotation
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]:         /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubelet/certificate/transport.go:99 +0x27a
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: goroutine 79 [copystack]:
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: github.com/openshift/origin/vendor/k8s.io/client-go/util/certificate.(*manager).rotateCerts(0xc00027e540, 0x43123a, 0x743ef58, 0x0)
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]:         /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/client-go/util/certificate/certificate_manager.go:408 +0x8f5
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection(0xc0003ec5d8, 0x5f18c400, 0x0, 0x0)
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]:         /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:211 +0x6f
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x77359400, 0x4000000000000000, 0x3fb999999999999a, 0x5, 0x0, 0xc00007cdd8, 0xffffffffffffff58, 0x0)
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]:         /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:399 +0x55
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: github.com/openshift/origin/vendor/k8s.io/client-go/util/certificate.(*manager).Start.func1()
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]:         /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/client-go/util/certificate/certificate_manager.go:317 +0x199
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000240a40)
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]:         /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5e
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000240a40, 0x4b07d80, 0xc000936000, 0x408401, 0xc0001b2360)
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]:         /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xa3
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000240a40, 0x3b9aca00, 0x0, 0xc0003ec701, 0xc0001b2360)
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]:         /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0xaa
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc000240a40, 0x3b9aca00, 0xc0001b2360)
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]:         /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: created by github.com/openshift/origin/vendor/k8s.io/client-go/util/certificate.(*manager).Start
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]:         /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/client-go/util/certificate/certificate_manager.go:285 +0xde
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: goroutine 80 [chan receive]:
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: github.com/openshift/origin/vendor/k8s.io/client-go/util/workqueue.(*Type).updateUnfinishedWorkLoop(0xc00038fd40)
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]:         /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/client-go/util/workqueue/queue.go:198 +0xe0
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: created by github.com/openshift/origin/vendor/k8s.io/client-go/util/workqueue.newQueue
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]:         /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/client-go/util/workqueue/queue.go:58 +0x132
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: goroutine 81 [select]:
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: github.com/openshift/origin/vendor/k8s.io/client-go/util/workqueue.(*delayingType).waitingLoop(0xc00038fe60)
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]:         /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/client-go/util/workqueue/delaying_queue.go:222 +0x405
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: created by github.com/openshift/origin/vendor/k8s.io/client-go/util/workqueue.NewDelayingQueueWithCustomClock
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]:         /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/client-go/util/workqueue/delaying_queue.go:58 +0x1ae
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: goroutine 130 [runnable]:
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/dynamiccertificates.(*DynamicFileCAContent).Run(0xc00038fec0, 0x1, 0xc0000ba9c0)
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]:         /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/dynamiccertificates/dynamic_cafile_content.go:163
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]: created by github.com/openshift/origin/vendor/k8s.io/kubernetes/cmd/kubelet/app.BuildAuthn.func1
Jul 22 23:00:04 cloud-c86k7-master-2 hyperkube[4413]:         /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/cmd/kubelet/app/auth.go:97 +0x60
Jul 22 23:00:04 cloud-c86k7-master-2 systemd[1]: kubelet.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

@jcpowermac have you seen anything like that on vSphere IPI?

**Comment by vrutkovs** [comment]
Also in crio.log:
>Jul 23 00:38:10 localhost crio[22902]: Inconsistency detected by ld.so: ../sysdeps/x86_64/dl-machine.h: 541: elf_machine_rela_relative: Assertion `ELFW(R_TYPE) (reloc->r_info) == R_X86_64_RELATIVE' failed!

**Comment by jcpowermac** [comment]
> kubelet panics:
> 
> @jcpowermac have you seen anything like that on vSphere IPI?

I haven't seen anything like that in our labs or CI.

**Comment by vrutkovs** [comment]
Is this still happening on recent OKD 4.5 stable releases?
