### ISSUE TITLE
Azure: Image registry pods crashloop

### ISSUE THREAD

**Issue by jomeier** [openshift/okd#62]
Hi,

I got OKD 4.4 running on Azure.

The image registry pods are crashlooping with:

```
asdf@DESKTOP-DFP5QD2K:~/okd4-test2$ oc logs -n openshift-image-registry image-registry-5776778f6-bpzn8
time="2020-02-02T22:23:22.741869875Z" level=info msg="start registry" distribution_version=v2.6.0+unknown go.version=go1.12.9 openshift_version=v3.11.0+2e1b031-153-dirty
time="2020-02-02T22:23:22.742444125Z" level=info msg="caching project quota objects with TTL 1m0s" go.version=go1.12.9
panic: Put https://c1okd4dlvnfxhm27.blob.core.windows.net/c1-okd4-dlvnf-image-registry-yoqupotnxuwkixbslbwvlpstnidceaobv?restype=container: dial tcp: i/o timeout

goroutine 1 [running]:
github.com/openshift/image-registry/vendor/github.com/docker/distribution/registry/handlers.NewApp(0x1f15fe0, 0xc0000ba058, 0xc000416000, 0xc000596180)
        /go/src/github.com/openshift/image-registry/vendor/github.com/docker/distribution/registry/handlers/app.go:127 +0x31ac
github.com/openshift/image-registry/pkg/dockerregistry/server/supermiddleware.NewApp(0x1f15fe0, 0xc0000ba058, 0xc000416000, 0x1f1d9e0, 0xc0005b8900, 0x1f28c00)
        /go/src/github.com/openshift/image-registry/pkg/dockerregistry/server/supermiddleware/app.go:96 +0x85
github.com/openshift/image-registry/pkg/dockerregistry/server.NewApp(0x1f15fe0, 0xc0000ba058, 0x1ee96c0, 0xc0000be668, 0xc000416000, 0xc0005ecd20, 0x0, 0x0, 0x0, 0xc000050000)
        /go/src/github.com/openshift/image-registry/pkg/dockerregistry/server/app.go:138 +0x2d4
github.com/openshift/image-registry/pkg/cmd/dockerregistry.NewServer(0x1f15fe0, 0xc0000ba058, 0xc000416000, 0xc0005ecd20, 0x0, 0x0, 0x1f563e0)
        /go/src/github.com/openshift/image-registry/pkg/cmd/dockerregistry/dockerregistry.go:210 +0x1c2
github.com/openshift/image-registry/pkg/cmd/dockerregistry.Execute(0x1ed4d20, 0xc0000be150)
        /go/src/github.com/openshift/image-registry/pkg/cmd/dockerregistry/dockerregistry.go:164 +0xa42
main.main()
        /go/src/github.com/openshift/image-registry/cmd/dockerregistry/main.go:93 +0x49c
```

A seperate storage class and container for the image registry are created. But the container is empty.

Greetings,

Josef

**Comment by vrutkovs** [comment]
Could you collect other settings via `oc adm must-gather`?

**Comment by jomeier** [comment]
Already have done that. But it's more than 28 MByte compressed :-) Have to split it in parts...

**Comment by jomeier** [comment]
[must-gather-ac.txt](https://github.com/openshift/okd/files/4145588/must-gather-ac.txt)
[must-gather-ab.txt](https://github.com/openshift/okd/files/4145590/must-gather-ab.txt)
[must-gather-aa.txt](https://github.com/openshift/okd/files/4145593/must-gather-aa.txt)

**Comment by jomeier** [comment]
Join the tree files with join, please.

**Comment by jomeier** [comment]
I deleted the pod image-registry-xxxxxxxx in namespace openshift-image-registry. Afterwards it came up correctly.

**Comment by LorbusChris** [comment]
xref: https://github.com/openshift/okd/issues/13

**Comment by jomeier** [comment]
@vrutkovs:
I haven't seen image registry crashloops again since then. In my opinion this one can be closed.

**Comment by vrutkovs** [comment]
Agree, lets file new issues if this occurs again on the newest FCOS
